### ISSUE TITLE
npm install fails on Windows

### ISSUE THREAD

**Issue by Hailong** [zixia/git-scripts#9]
v0.2.1

The error is `'.' is not recognized as an internal or external command.`

![wechatimg858](https://user-images.githubusercontent.com/354776/35746784-f9ee07f4-0815-11e8-8797-5f810708645e.png)

**Comment by zixia** [comment]
I'm also experiencing this issue because I just switch my pre-push hook to using git-scripts.

**Comment by zixia** [comment]
I just have a look at the code and saw there's already a fix for this issue:
https://github.com/nkzawa/git-scripts/commit/84f68ad7c29f7c518b1c3e4d253ed03237bef38a

But it seems not published in NPM.

Please update, thanks! @nkzawa

**Comment by zixia** [comment]
ping @nkzawa

**Comment by shrpne** [comment]
84f68ad still fails for me with "symlink not permitted"

I assume something like #8 is needed to make it work

**Comment by zixia** [comment]
@nkzawa Please update the npm package with the latest code, thanks!

**Comment by Adam-Kernig-RM** [comment]
+ 1 for this, can it be updated please. This tool is helpful for our mac Devs however Windows devs are suffering

**Comment by Adam-Kernig-RM** [comment]
@nkzawa +1

**Comment by huan** [comment]
ping @nkzawa

**Comment by FMGordillo** [comment]
+1

**Comment by MalteMagnussen** [comment]
I'm currently having the same issue. 
![image](https://user-images.githubusercontent.com/11192971/68992969-8b9f7a80-0872-11ea-968e-019c1ccf6304.png)

Is there a fix? Please @ me.

**Comment by SRSaddler** [comment]
+1 please add update

**Comment by huan** [comment]
ping @nkzawa

**Comment by huan** [comment]
I have published the latest master branch with all the PRs(thanks all!) with version 0.4.3

Please feel free to let me know if there are any problems.
